#!/usr/bin/env python
import argparse
import sys
import os

ncd_root = os.path.dirname(os.path.abspath(sys.argv[0]))
ncd_pkg = os.path.join(ncd_root, 'netcontrold')
sys.path.insert(0, ncd_pkg)

from netcontrold.app import ncd
from netcontrold.lib import util

USAGE = "ncd_ctl [start/stop/restart]\n"

if ((len(sys.argv) != 2) or
        (sys.argv[1] not in ('start', 'stop', 'restart'))):
    sys.stderr.write(USAGE)
    sys.exit(1)

main_srv = util.Service(ncd.ncd_main,
                        ['-s', '10', '-q'],
                        '/var/run/ncd.pid')

if sys.argv[1] == 'start':
    main_srv.start()
elif sys.argv[1] == 'restart':
    main_srv.restart()
elif sys.argv[1] == 'stop':
    main_srv.stop()
    
sys.exit(0)

