FROM rhel7:latest
LABEL version=1.0
LABEL maintainer="Gowrishankar Muthukrishnan <gmuthukr@redhat.com>"

RUN yum install -y --enablerepo="rhel-7-fast-datapath-rpms" openvswitch python3-pip && \
    yum clean all
RUN pip3 install netcontrold
ENTRYPOINT ["/usr/local/bin/ncd_watch"]
